"""added goal_completed_at

Revision ID: 89b84c65181e
Revises: 3d2dd1711e99
Create Date: 2022-01-21 13:06:16.804468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89b84c65181e'
down_revision = '3d2dd1711e99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal', sa.Column('goal_completed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goal', 'goal_completed_at')
    # ### end Alembic commands ###
